/// Neli WHO GAPPA suunda.
table dim_policies
	lineageTag: 2beeb180-69d2-49dd-b480-ea092ff6a0ba

	column direction_id
		dataType: int64
		isHidden
		isKey
		lineageTag: c08c793a-cf6d-487d-bdb3-9983e714cc8e
		summarizeBy: none
		sourceColumn: direction_id

	column 'Suuna kood'
		dataType: int64
		isHidden
		lineageTag: 066342c4-a668-4622-b872-1c8c74efe45b
		summarizeBy: none
		sourceColumn: Suuna kood

	/// Neli suunda: aktiivne ühiskond, keskkond, inimene, struktuurid.
	column Suund
		dataType: string
		lineageTag: df7174b0-a4e8-46d7-956b-259bca3e4cc8
		summarizeBy: none
		sourceColumn: Suund
		sortByColumn: 'Suuna kood'

	column Kirjeldus
		dataType: string
		lineageTag: 0f417ae7-3360-425a-8825-5d2751ec86d2
		summarizeBy: none
		sourceColumn: Kirjeldus

	partition dim_policies = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://app.liigume.ee/api/policies")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "policy_measure", "direction_code", "description", "is_direction"}, {"id", "policy_measure", "direction_code", "description", "is_direction"}),
				    #"Changed Type is_direction" = Table.TransformColumnTypes(#"Expanded Column1", {{"is_direction", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type is_direction", each [is_direction] = 1),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows", {"id", "policy_measure", "direction_code", "description"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns", {{"id", "direction_id"}, {"policy_measure", "Suund"}, {"direction_code", "Suuna kood"}, {"description", "Kirjeldus"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"direction_id", Int64.Type}, {"Suund", type text}, {"Suuna kood", Int64.Type}, {"Kirjeldus", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

