table fact_sales
	lineageTag: 9572edba-8f56-4b72-9ac9-75bec4ad2f3e

	measure Müük = SUMX(fact_sales, fact_sales[Quantity] * fact_sales[UnitPrice] * (1 - fact_sales[Discount]))
		formatString: #,0.00
		lineageTag: 8a4c91d2-6e30-4b75-9f18-2d5a7c0e4b91

	column SaleID
		dataType: string
		lineageTag: a683fecb-9067-4c83-8bda-86cfd5be304f
		summarizeBy: none
		sourceColumn: SaleID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7940fdc-a178-4d94-9ceb-97dae6cf4150
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: c8a510ed-b289-4ea5-8dfc-a8ebf7d05261
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: d9b621fe-c390-4fb6-9ead-b9fc08e16372
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: eac7320f-d4a1-40c7-8fbe-ca0d19f27483
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: fbd84310-e5b2-41d8-9acf-db1e20a38594
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		formatString: 0%
		lineageTag: 0ce95421-f6c3-42e9-8bd0-ec2f31b496a5
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: string
		lineageTag: 1dfa6532-07d4-43f0-9ce1-fd3042c5a7b6
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: string
		lineageTag: 2e0b7643-18e5-4401-8df2-0e4153d6b8c7
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\emiliea\Documents\GitHub\andmetarkus\Materjalid\Day15 AI\Sales data\SalesTable.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"SaleID", type text}, {"Date", type date}, {"CustomerID", type text}, {"ProductID", type text}, {"Quantity", Int64.Type}, {"SalesRepID", type text}, {"RegionID", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"UnitPrice", type number}, {"Discount", type number}}, "en-US")
				in
				    #"Changed Type with Locale"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

