table dim_product
	lineageTag: b73409f6-a172-4d28-9e4b-3d708c2f4130

	column ProductID
		dataType: string
		lineageTag: c84510a7-b283-4e39-8f5c-4e819d305241
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: d95621b8-c394-4f40-9a6d-5f920e416352
		isDefaultLabel
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ea6732c9-d4a5-4061-8b7e-6a031f527463
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column CostPrice
		dataType: double
		lineageTag: fb7843d0-e5b6-4172-9c8f-7b142a638574
		summarizeBy: none
		sourceColumn: CostPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Manufacturer
		dataType: string
		lineageTag: 0c8954e1-f6c7-4283-8d90-8c253b749685
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\emiliea\Documents\GitHub\andmetarkus\Materjalid\Day15 AI\Sales data\ProductTable.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"Manufacturer", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"CostPrice", type number}}, "en-US")
				in
				    #"Changed Type with Locale"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

